#REServer YAML config file

#REServer Net Config
net:
  #listen_uri: unix:/tmp/redis.sock
  listen_uri: tcp://127.0.0.1:6380
  multicore: true
  reuse_port: true
  lock_os_thread: false
  read_buffer_cap: 0

#REServer memory cache related parameters
cache:
  enable: false
  max_items_size: 2048 #The maximum number of items stored in the Cache
  default_expiration: 5000 # Cache kv default expiration time (unit: milliseconds)
  cleanup_interval: 120 #Cache memory cleaning cycle (unit: seconds)

#REServer api config
api:
  http_listen_address:

#REServer Debug option
debug:
  enable: false
  pprof_uri: "127.0.0.1:6060"

memory_db:
  data_path: ""  #Defaults to empty string which means no data will get persisted.
  partition_duration: "1h"  # specifies the timestamp range of partitions.Defaults to 1h
  retention: "14d" # specifies when to remove old data.
  timestamp_precision: "ms"  # specifies the precision of timestamps to be used by all operations.Defaults to Milliseconds
  write_timeout: "30s" # specifies the timeout to wait when workers are busy.Defaults to 30s.
  wal_buffered_size: 4096 # WithWAL specifies the buffered byte size before flushing a WAL file.-1 disables using WAL.0 means it writes to a file whenever data point comes in.

memory_db:
  partitionDuration:
